import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "admin Page: Create Next App",
  description: "Generated by create next admin page",
};

export default function AdminLayout({ children }) {
  return (
    <>
        <span>Admin Navbar</span>
        {children}
    </>
  );
}
